
spring.rabbitmq:
  listener.simple.retry:
    enabled: true
    initial-interval: 2s
    max-attempts: 30
    max-interval: 300s
    multiplier: 2
  addresses: ${AMQP_ADDRESSES:${app.amqp.addresses}}
  username: ${AMQP_USERNAME:${app.amqp.username:}}
  password: ${AMQP_PASSWORD:${app.amqp.password:}}
  virtual-host: ${app.amqp.vhost:${AMQP_VHOST:/}}
  ssl.enabled: ${app.amqp.ssl.enabled:false}
  ssl.algorithm: ${app.amqp.ssl.algorithm:TLSv1.2}
  ssl.key-store: ${app.amqp.ssl.key-store:}
  ssl.key-store-password: ${app.amqp.ssl.key-store-password:}
  ssl.trust-store: ${app.amqp.ssl.trust-store:}
  ssl.trust-store-password: ${app.amqp.ssl.trust-store-password:}

app.amqp:
  enabled: true
  exchange: app
  routing: services

